package vendingmachine;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MainPage extends javax.swing.JFrame {
    Payment pymnt = new Payment(); 
    Selection select = new Selection();
    Customer cc = new Customer();
    DefaultTableModel model ;
    
    public MainPage(Customer c1) {
        initComponents();
        Name.setText(c1.getName());
        cc.setName(Name.getText());
    }
    
    public MainPage() {
        initComponents();
    }
    
    public void nextPage(){
        Receipt rcpt = new Receipt(cc,pymnt,select);
        rcpt.setVisible(true);
        dispose();
    }
    
    public void clearSelection(){
        boxProductID.setSelectedItem("00");
        txtQuantity.setText(null);
        txtPrice.setText(null);
        txtMoney.setText(null);
        totalInsertMoney.setText("0");
    }
    
    public void receipt(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlTop = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        lblTiitle = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlSide = new javax.swing.JPanel();
        pnlSelection = new javax.swing.JPanel();
        lblSelection = new javax.swing.JLabel();
        lblProductID = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnApply = new javax.swing.JButton();
        boxProductID = new javax.swing.JComboBox<>();
        pnlListItem = new javax.swing.JPanel();
        lblPayment = new javax.swing.JLabel();
        lblTypeOfPayment = new javax.swing.JLabel();
        boxPayment = new javax.swing.JComboBox<>();
        lblMoneyIinsert = new javax.swing.JLabel();
        txtMoney = new javax.swing.JTextField();
        lblComment = new javax.swing.JLabel();
        lblTotalInsertMoney = new javax.swing.JLabel();
        totalInsertMoney = new javax.swing.JLabel();
        btnAddMore = new javax.swing.JButton();
        scrlpnlCash = new javax.swing.JScrollPane();
        tblCash = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();
        scrlPanel = new javax.swing.JScrollPane();
        pnlDisplay = new javax.swing.JPanel();
        pnlProduct1 = new javax.swing.JPanel();
        lblIconProduct1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblID1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Aavailability1 = new javax.swing.JTextField();
        lblWeiight = new javax.swing.JLabel();
        pnlProduct2 = new javax.swing.JPanel();
        lblIconProduct2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblID2 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        ProductPrice2 = new javax.swing.JLabel();
        Aavailability2 = new javax.swing.JTextField();
        lblWeiight2 = new javax.swing.JLabel();
        pnlProduct3 = new javax.swing.JPanel();
        lblIconProduct3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblID3 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        ProductPrice3 = new javax.swing.JLabel();
        Aavailability3 = new javax.swing.JTextField();
        lblWeiight3 = new javax.swing.JLabel();
        pnlProduct4 = new javax.swing.JPanel();
        lblIconProduct4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblID4 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        ProductPrice4 = new javax.swing.JLabel();
        Aavailability4 = new javax.swing.JTextField();
        lblWeiight4 = new javax.swing.JLabel();
        pnlProduct5 = new javax.swing.JPanel();
        lblIconProduct5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblID5 = new javax.swing.JLabel();
        lblName5 = new javax.swing.JLabel();
        ProductPrice5 = new javax.swing.JLabel();
        Aavailability5 = new javax.swing.JTextField();
        lblWeiight5 = new javax.swing.JLabel();
        pnlProduct6 = new javax.swing.JPanel();
        lblIconProduct6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblID6 = new javax.swing.JLabel();
        lblName6 = new javax.swing.JLabel();
        ProductPrice6 = new javax.swing.JLabel();
        Aavailability6 = new javax.swing.JTextField();
        lblWeiight6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTop.setBackground(new java.awt.Color(238, 197, 109));
        pnlTop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/smallLogo.png"))); // NOI18N

        txtTitle.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtTitle.setText("Vending ");

        lblTiitle.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblTiitle.setText("Machine");

        Name.setBackground(new java.awt.Color(255, 255, 255));
        Name.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Name.setText("XXXXXXX");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("Welcome,");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitle)
                    .addComponent(lblTiitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name)
                .addGap(18, 18, 18))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIcon))
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtTitle)
                        .addGap(0, 0, 0)
                        .addComponent(lblTiitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Name))
                .addGap(19, 19, 19))
        );

        pnlSide.setBackground(new java.awt.Color(255, 255, 255));

        pnlSelection.setBackground(new java.awt.Color(255, 255, 255));
        pnlSelection.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSelection.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblSelection.setText("Selection");

        lblProductID.setText("Product ID : ");

        lblQuantity.setText("Quantity     : ");

        lblPrice.setText("Price          : RM");

        txtPrice.setEditable(false);
        txtPrice.setText("0");
        txtPrice.setToolTipText("");

        btnApply.setBackground(new java.awt.Color(238, 197, 109));
        btnApply.setText("Confirm");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        boxProductID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06" }));

        javax.swing.GroupLayout pnlSelectionLayout = new javax.swing.GroupLayout(pnlSelection);
        pnlSelection.setLayout(pnlSelectionLayout);
        pnlSelectionLayout.setHorizontalGroup(
            pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectionLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlSelectionLayout.createSequentialGroup()
                                    .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(pnlSelectionLayout.createSequentialGroup()
                                .addComponent(lblProductID)
                                .addGap(27, 27, 27)))
                        .addGroup(pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(txtPrice)
                            .addComponent(boxProductID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblSelection)
                    .addComponent(btnApply, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSelectionLayout.setVerticalGroup(
            pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductID)
                    .addComponent(boxProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnApply)
                .addContainerGap())
        );

        pnlListItem.setBackground(new java.awt.Color(255, 255, 255));
        pnlListItem.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPayment.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblPayment.setText("Payment");

        lblTypeOfPayment.setText("Type of Payment : ");

        boxPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "PayPal" }));
        boxPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPaymentActionPerformed(evt);
            }
        });

        lblMoneyIinsert.setText("Insert Money**     : RM");

        lblComment.setForeground(new java.awt.Color(255, 0, 0));
        lblComment.setText("**10$ /20$ /50$ /RM1 /RM5 only");

        lblTotalInsertMoney.setText("Total Insert Money : RM");

        totalInsertMoney.setText("0");

        btnAddMore.setBackground(new java.awt.Color(238, 197, 109));
        btnAddMore.setText("Add Money");
        btnAddMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMoreActionPerformed(evt);
            }
        });

        tblCash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inserted Cash"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrlpnlCash.setViewportView(tblCash);

        javax.swing.GroupLayout pnlListItemLayout = new javax.swing.GroupLayout(pnlListItem);
        pnlListItem.setLayout(pnlListItemLayout);
        pnlListItemLayout.setHorizontalGroup(
            pnlListItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListItemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlpnlCash, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnAddMore, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlListItemLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlListItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlListItemLayout.createSequentialGroup()
                                .addComponent(lblMoneyIinsert)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlListItemLayout.createSequentialGroup()
                                .addComponent(lblTypeOfPayment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boxPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblPayment)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListItemLayout.createSequentialGroup()
                        .addComponent(lblTotalInsertMoney)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalInsertMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblComment, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlListItemLayout.setVerticalGroup(
            pnlListItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListItemLayout.createSequentialGroup()
                .addComponent(lblPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypeOfPayment)
                    .addComponent(boxPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoneyIinsert)
                    .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddMore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlpnlCash, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalInsertMoney)
                    .addComponent(totalInsertMoney))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnPurchase.setBackground(new java.awt.Color(238, 197, 109));
        btnPurchase.setText("Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSideLayout = new javax.swing.GroupLayout(pnlSide);
        pnlSide.setLayout(pnlSideLayout);
        pnlSideLayout.setHorizontalGroup(
            pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideLayout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlListItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSelection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPurchase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSideLayout.setVerticalGroup(
            pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        pnlDisplay.setBackground(new java.awt.Color(242, 242, 242));

        pnlProduct1.setBackground(new java.awt.Color(255, 255, 255));

        lblIconProduct1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KitKat.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblID1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblID1.setForeground(new java.awt.Color(238, 197, 109));
        lblID1.setText("01");

        lblName1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblName1.setText("KitKat");

        jLabel1.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        jLabel1.setText("RM2.50");

        Aavailability1.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        Aavailability1.setForeground(new java.awt.Color(0, 153, 0));
        Aavailability1.setText(" Available ");
        Aavailability1.setAlignmentX(1.0F);
        Aavailability1.setAlignmentY(1.0F);
        Aavailability1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));

        lblWeiight.setText("100g");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblID1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWeiight))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Aavailability1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID1)
                    .addComponent(lblName1)
                    .addComponent(lblWeiight))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Aavailability1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlProduct1Layout = new javax.swing.GroupLayout(pnlProduct1);
        pnlProduct1.setLayout(pnlProduct1Layout);
        pnlProduct1Layout.setHorizontalGroup(
            pnlProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconProduct1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlProduct1Layout.setVerticalGroup(
            pnlProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconProduct1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlProduct2.setBackground(new java.awt.Color(255, 255, 255));

        lblIconProduct2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cloud9.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblID2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblID2.setForeground(new java.awt.Color(238, 197, 109));
        lblID2.setText("02");

        lblName2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblName2.setText("KitKat");

        ProductPrice2.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        ProductPrice2.setText("RM0.50");

        Aavailability2.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        Aavailability2.setForeground(new java.awt.Color(0, 153, 0));
        Aavailability2.setText(" Available ");
        Aavailability2.setAlignmentX(1.0F);
        Aavailability2.setAlignmentY(1.0F);
        Aavailability2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));

        lblWeiight2.setText("120g");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblID2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWeiight2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ProductPrice2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Aavailability2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID2)
                    .addComponent(lblName2)
                    .addComponent(lblWeiight2))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductPrice2)
                    .addComponent(Aavailability2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlProduct2Layout = new javax.swing.GroupLayout(pnlProduct2);
        pnlProduct2.setLayout(pnlProduct2Layout);
        pnlProduct2Layout.setHorizontalGroup(
            pnlProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconProduct2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlProduct2Layout.setVerticalGroup(
            pnlProduct2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconProduct2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlProduct3.setBackground(new java.awt.Color(255, 255, 255));

        lblIconProduct3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cadbury.jpg"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblID3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblID3.setForeground(new java.awt.Color(238, 197, 109));
        lblID3.setText("03");

        lblName3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblName3.setText("CadBury");

        ProductPrice3.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        ProductPrice3.setText("RM1.20");

        Aavailability3.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        Aavailability3.setForeground(new java.awt.Color(0, 153, 0));
        Aavailability3.setText(" Available ");
        Aavailability3.setAlignmentX(1.0F);
        Aavailability3.setAlignmentY(1.0F);
        Aavailability3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));

        lblWeiight3.setText("150g");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblID3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWeiight3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ProductPrice3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Aavailability3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID3)
                    .addComponent(lblName3)
                    .addComponent(lblWeiight3))
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductPrice3)
                    .addComponent(Aavailability3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlProduct3Layout = new javax.swing.GroupLayout(pnlProduct3);
        pnlProduct3.setLayout(pnlProduct3Layout);
        pnlProduct3Layout.setHorizontalGroup(
            pnlProduct3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconProduct3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlProduct3Layout.setVerticalGroup(
            pnlProduct3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconProduct3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlProduct4.setBackground(new java.awt.Color(255, 255, 255));

        lblIconProduct4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Coke.jpg"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblID4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblID4.setForeground(new java.awt.Color(238, 197, 109));
        lblID4.setText("04");

        lblName4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblName4.setText("Coke");

        ProductPrice4.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        ProductPrice4.setText("RM1.50");

        Aavailability4.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        Aavailability4.setForeground(new java.awt.Color(0, 153, 0));
        Aavailability4.setText(" Available ");
        Aavailability4.setAlignmentX(1.0F);
        Aavailability4.setAlignmentY(1.0F);
        Aavailability4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));

        lblWeiight4.setText("250ml");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblID4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWeiight4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ProductPrice4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Aavailability4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID4)
                    .addComponent(lblName4)
                    .addComponent(lblWeiight4))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductPrice4)
                    .addComponent(Aavailability4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlProduct4Layout = new javax.swing.GroupLayout(pnlProduct4);
        pnlProduct4.setLayout(pnlProduct4Layout);
        pnlProduct4Layout.setHorizontalGroup(
            pnlProduct4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconProduct4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlProduct4Layout.setVerticalGroup(
            pnlProduct4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconProduct4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlProduct5.setBackground(new java.awt.Color(255, 255, 255));

        lblIconProduct5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/100Plus.jpg"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lblID5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblID5.setForeground(new java.awt.Color(238, 197, 109));
        lblID5.setText("05");

        lblName5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblName5.setText("100Plus");

        ProductPrice5.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        ProductPrice5.setText("RM2.00");

        Aavailability5.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        Aavailability5.setForeground(new java.awt.Color(204, 0, 0));
        Aavailability5.setText(" Not Available");
        Aavailability5.setAlignmentX(1.0F);
        Aavailability5.setAlignmentY(1.0F);
        Aavailability5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));

        lblWeiight5.setText("120ml");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblID5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWeiight5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ProductPrice5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Aavailability5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID5)
                    .addComponent(lblName5)
                    .addComponent(lblWeiight5))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductPrice5)
                    .addComponent(Aavailability5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlProduct5Layout = new javax.swing.GroupLayout(pnlProduct5);
        pnlProduct5.setLayout(pnlProduct5Layout);
        pnlProduct5Layout.setHorizontalGroup(
            pnlProduct5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlProduct5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconProduct5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlProduct5Layout.setVerticalGroup(
            pnlProduct5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconProduct5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlProduct6.setBackground(new java.awt.Color(255, 255, 255));

        lblIconProduct6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fanta.jpg"))); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lblID6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblID6.setForeground(new java.awt.Color(238, 197, 109));
        lblID6.setText("06");

        lblName6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblName6.setText("Fanta");

        ProductPrice6.setFont(new java.awt.Font("sansserif", 2, 14)); // NOI18N
        ProductPrice6.setText("RM2.30");

        Aavailability6.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        Aavailability6.setForeground(new java.awt.Color(0, 153, 0));
        Aavailability6.setText(" Available ");
        Aavailability6.setAlignmentX(1.0F);
        Aavailability6.setAlignmentY(1.0F);
        Aavailability6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 2, true));

        lblWeiight6.setText("150ml");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblID6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWeiight6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ProductPrice6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Aavailability6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID6)
                            .addComponent(lblName6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWeiight6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductPrice6)
                    .addComponent(Aavailability6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlProduct6Layout = new javax.swing.GroupLayout(pnlProduct6);
        pnlProduct6.setLayout(pnlProduct6Layout);
        pnlProduct6Layout.setHorizontalGroup(
            pnlProduct6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconProduct6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlProduct6Layout.setVerticalGroup(
            pnlProduct6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProduct6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconProduct6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlDisplayLayout = new javax.swing.GroupLayout(pnlDisplay);
        pnlDisplay.setLayout(pnlDisplayLayout);
        pnlDisplayLayout.setHorizontalGroup(
            pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDisplayLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlProduct5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProduct3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlProduct6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlProduct4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
        );
        pnlDisplayLayout.setVerticalGroup(
            pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDisplayLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlProduct5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlProduct6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        scrlPanel.setViewportView(pnlDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        ThankYou ty = new ThankYou();
        ty.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearSelection();
        model.setRowCount(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        Product[] products = new Product[6]; //Polymorphysm
        products[0]= new Food("01","Kitkat",2.50,10,100);
        products[1]= new Food("02","Cloud9",0.50,14,120);
        products[2]= new Food("03","CadBury",1.20,15,150);
        products[3]= new Drink("04","Coke",1.50,7,150);
        products[4]= new Drink("05","100Plus",2.00,0,120);
        products[5]= new Drink("06","Fanta",2.30,19,200);
        
        if(boxProductID.getSelectedItem().equals("00")){
            JOptionPane.showMessageDialog(null,"Please Select Product ID!", "Error",JOptionPane.ERROR_MESSAGE);
            clearSelection();
        }else if(txtQuantity.getText().equals("0") || txtQuantity.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please Insert Quantity of Product!", "Error",JOptionPane.ERROR_MESSAGE);
            clearSelection();
        }else {
            select.setQuantity(Integer.parseInt(txtQuantity.getText()));  
            
            //Calculate total price for product
            for(int i=0;i<products.length;i++){
                if(boxProductID.getSelectedItem().equals(products[i].getID())){
                    if("Not Available".equals(products[i].displayStatus())){
                        JOptionPane.showMessageDialog(null,"Sorry, Item is not Available!", "Error",JOptionPane.ERROR_MESSAGE);
                    } else if(products[i].getQuantityInMachine()<Integer.parseInt(txtQuantity.getText())){
                        JOptionPane.showMessageDialog(null,"Sorry, there is "+products[i].getQuantityInMachine()+" only in machine", "Error",JOptionPane.ERROR_MESSAGE);
                    }else{
                        txtPrice.setText(String.valueOf(new DecimalFormat("0.00").format(select.calcTotalPrice(products[i].getPrice()))));
                        
                        select.setProductID(products[i]);
                        select.setQuantity(Integer.parseInt(txtQuantity.getText()));
                        select.setTotalPrice(Double.parseDouble(txtPrice.getText()));
                        
                    }
                }
            }
            
            
        }
    }//GEN-LAST:event_btnApplyActionPerformed

    private void boxPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPaymentActionPerformed
        String selectedvalue = boxPayment.getSelectedItem().toString();

        if("PayPal".equals(selectedvalue)){
            pymnt.setPymntType( boxPayment.getSelectedItem().toString());
            lblTotalInsertMoney.setVisible(false);
            totalInsertMoney.setVisible(false);
            lblComment.setVisible(false);
            btnAddMore.setVisible(false);
            tblCash.setVisible(false);
            scrlpnlCash.setVisible(false);
        } else if("Cash".equals(selectedvalue)){
            pymnt.setPymntType("Cash");
            lblTotalInsertMoney.setVisible(true);
            totalInsertMoney.setVisible(true);
            lblComment.setVisible(true);
            btnAddMore.setVisible(true);
            tblCash.setVisible(true);
            scrlpnlCash.setVisible(true);
        }
    }//GEN-LAST:event_boxPaymentActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed

        if(select.getTotalPrice()==0){
            JOptionPane.showMessageDialog(null,"Please Select a Product!", "Error",JOptionPane.ERROR_MESSAGE);
        }else if(pymnt.getPymntType().equals("PayPal")){
           double pmoney = Double.parseDouble(txtMoney.getText());
           pymnt.setTotalMoney(pmoney);
            
            if(select.getTotalPrice()>pmoney){
                JOptionPane.showMessageDialog(null,"Sorry, Please Insert More Money!", "Error",JOptionPane.ERROR_MESSAGE);
                txtMoney.setText(null);
            } else {
                pymnt.setTotalMoney(pmoney);
                pymnt.setPymntType((String) boxPayment.getSelectedItem());
                nextPage();
            }
        } else if(pymnt.getPymntType().equals("Cash")){
            double cmoney = pymnt.getTotalMoney();
            pymnt.setTotalMoney(cmoney);
            
            if(select.getTotalPrice()>cmoney){
                JOptionPane.showMessageDialog(null,"Sorry, Please Insert More Money!", "Error",JOptionPane.ERROR_MESSAGE);
                txtMoney.setText(null);
            } else {
                pymnt.setTotalMoney(cmoney);
                pymnt.setPymntType((String) boxPayment.getSelectedItem());
                nextPage();
            }
        }
        
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void btnAddMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMoreActionPerformed
        double sum=0,t;
        pymnt.setMoney(Double.parseDouble(txtMoney.getText()));
        double mny =pymnt.totalMoney();
        totalInsertMoney.setText(String.valueOf(new DecimalFormat("0.00").format(mny)));
        
        pymnt = new Payment(mny);
        model =(DefaultTableModel)tblCash.getModel();
        model.addRow(new Object[]{mny});
        txtMoney.setText(null);
        
        for(int i=0;i<tblCash.getRowCount();i++){
            sum=sum+Double.parseDouble(tblCash.getValueAt(i, 0).toString());
        }
        totalInsertMoney.setText(String.valueOf(new DecimalFormat("0.00").format(sum)));
        
        t=Double.parseDouble(totalInsertMoney.getText());
        pymnt.setTotalMoney(t);
        
        pymnt.setPymntType("Cash");
    }//GEN-LAST:event_btnAddMoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Aavailability1;
    private javax.swing.JTextField Aavailability2;
    private javax.swing.JTextField Aavailability3;
    private javax.swing.JTextField Aavailability4;
    private javax.swing.JTextField Aavailability5;
    private javax.swing.JTextField Aavailability6;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel ProductPrice2;
    private javax.swing.JLabel ProductPrice3;
    private javax.swing.JLabel ProductPrice4;
    private javax.swing.JLabel ProductPrice5;
    private javax.swing.JLabel ProductPrice6;
    private javax.swing.JComboBox<String> boxPayment;
    private javax.swing.JComboBox<String> boxProductID;
    private javax.swing.JButton btnAddMore;
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblComment;
    private javax.swing.JLabel lblID1;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblID3;
    private javax.swing.JLabel lblID4;
    private javax.swing.JLabel lblID5;
    private javax.swing.JLabel lblID6;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIconProduct1;
    private javax.swing.JLabel lblIconProduct2;
    private javax.swing.JLabel lblIconProduct3;
    private javax.swing.JLabel lblIconProduct4;
    private javax.swing.JLabel lblIconProduct5;
    private javax.swing.JLabel lblIconProduct6;
    private javax.swing.JLabel lblMoneyIinsert;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSelection;
    private javax.swing.JLabel lblTiitle;
    private javax.swing.JLabel lblTotalInsertMoney;
    private javax.swing.JLabel lblTypeOfPayment;
    private javax.swing.JLabel lblWeiight;
    private javax.swing.JLabel lblWeiight2;
    private javax.swing.JLabel lblWeiight3;
    private javax.swing.JLabel lblWeiight4;
    private javax.swing.JLabel lblWeiight5;
    private javax.swing.JLabel lblWeiight6;
    private javax.swing.JPanel pnlDisplay;
    private javax.swing.JPanel pnlListItem;
    private javax.swing.JPanel pnlProduct1;
    private javax.swing.JPanel pnlProduct2;
    private javax.swing.JPanel pnlProduct3;
    private javax.swing.JPanel pnlProduct4;
    private javax.swing.JPanel pnlProduct5;
    private javax.swing.JPanel pnlProduct6;
    private javax.swing.JPanel pnlSelection;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JScrollPane scrlPanel;
    private javax.swing.JScrollPane scrlpnlCash;
    private javax.swing.JTable tblCash;
    private javax.swing.JLabel totalInsertMoney;
    private javax.swing.JTextField txtMoney;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
